version: "3.5"

services:
  api01: &api
    image: rinhaaot:latest
    depends_on:
      - db
    hostname: api01
    environment:
      - CONNECTION_STRING=Host=db;Database=rinha;Username=postgres;Password=postgres;
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "30MB"

  api02:
    <<: *api 
    hostname: api02
 
  nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - api01
        - api02
      ports:
        - "9999:9999"
      deploy:
        resources:
          limits:
            cpus: "0.15"
            memory: "20MB"

  # postgres
  db:
    image: postgres:latest
    hostname: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rinha
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0  -c effective_io_concurrency=20 -c work_mem=128MB 
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "470MB"

networks:
  default:
    driver: bridge